#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0.{build}

# version suffix, if any (e.g. '-RC1', '-beta' otherwise '')
environment:
  version_suffix: '-RC1'

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
- Visual Studio 2017
- Visual Studio 2019

# enable patching of Directory.Build.props
dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}$(version_suffix)'
  package_version: '{version}$(version_suffix)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- ps: .\tools\Prepare-Release.ps1

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- ps: .\tools\Run-Tests.ps1

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: .\*.zip
- path: .\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# Commented out as we need to create a new signing policy.
# deploy:
# - provider: Webhook
#   on:
#     ARTIFACT_SIGNING_ENABLED: true
#   url: https://app.signpath.io/API/v1/7c19b2cf-90f7-4d15-9b12-1b615f7c18c4/Integrations/AppVeyor?SigningPolicyId=5c9879c7-0dea-4303-8e5b-fc4192a7b0de
#   on_build_success: true
#   on_build_failure: false
#   on_build_status_changed: false
#   method: POST
#   authorization:
#      secure: RdmJQ3LAsGIbtqbxlcn7wF8ESTbPSDiR0Fmyt11mDl+avSDd0HKexHA+sWQA3cN1K8aVnKTzvjGTQS8DSDmLzQ==
