version: '{build}'

image: Visual Studio 2017

build_script:
- ps: .\tools\Prepare-Release.ps1

test_script:
- ps: .\tools\Run-Tests.ps1

artifacts:
- path: .\*.zip
- path: .\*.nupkg

# Commented out as we need to create a new signing policy.
# deploy:
# - provider: Webhook
#   on:
#     ARTIFACT_SIGNING_ENABLED: true
#   url: https://app.signpath.io/API/v1/7c19b2cf-90f7-4d15-9b12-1b615f7c18c4/Integrations/AppVeyor?SigningPolicyId=5c9879c7-0dea-4303-8e5b-fc4192a7b0de
#   on_build_success: true
#   on_build_failure: false
#   on_build_status_changed: false
#   method: POST
#   authorization:
#      secure: RdmJQ3LAsGIbtqbxlcn7wF8ESTbPSDiR0Fmyt11mDl+avSDd0HKexHA+sWQA3cN1K8aVnKTzvjGTQS8DSDmLzQ==